apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-nginx
  name: demo-nginx-svc
spec:
  type: NodePort
  selector:
    app: demo-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
